language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t tracer2020/docker-react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true tracer2020/docker-react-test npm run test

deploy:
    provider: elasticbeanstalk
    region: "eu-central-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-eu-central-1-295895857794"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
#just to add some comment
#AWS Beanstalk would automatically create an S3 bucket to store
#all the details of site's files (in my case, there was old bucket
#from certification times)
#
#after_success:
#    - docker build -t vladimirpodr/multi-client -f ./client
#    - docker build -t vladimirpodr/multi-nginx -f ./nginx
#    - docker build -t vladimirpodr/multi-server -f ./server
#    - docker build -t vladimirpodr/multi-worker -f ./worker
    #Login to the Docker CLI - comment was present initially
#    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #Push images to Docker Hub - comment was present initially
#    - docker push vladimirpodr/multi-client
#    - docker push vladimirpodr/multi-nginx
#    - docker push vladimirpodr/multi-server
#    - docker push vladimirpodr/multi-worker
